GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json
    
{   
    "title": "The Third blog post",
    "author": "Check The User",
    "url": "https://www.google..co.uk",
    "likes": 45,
    "user": "64c0ee97390b08e48521ba8a"
}

###

GET http://localhost:3001/api/users
content-type: application/json

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "newUser",
    "name": "theuser2",
    "password": "test123"
}

### 
DELETE http://localhost:3001/api/blogs/