GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVkLXJhZCIsImlkIjoiNjRjMDIyNzMyODQ4ZDUzZTkyYWIwZDkzIiwiaWF0IjoxNjkwMzc4MzczLCJleHAiOjE2OTAzODE5NzN9.YOQmiYSuE5ocGQ5NT_jtBRQxgXzROaJxwnCr2skN73Q

{   
    "title": "This is ed-rad's blog",
    "author": "ed-rad",
    "url": "https://www.google..co.uk",
    "likes": 50
}

###

GET http://localhost:3001/api/users
content-type: application/json

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "newUser",
    "name": "theuser2",
    "password": "test123"
}

### 

###
POST http://localhost:3001/api/login
content-type: application/json 

{
    "username": "ed-rad",
    "password": "test"
}

### 
DELETE http://localhost:3001/api/blogs/64c120fb4f981b9b651d6951
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVkLXJhZCIsImlkIjoiNjRjMDIyNzMyODQ4ZDUzZTkyYWIwZDkzIiwiaWF0IjoxNjkwMzc4NTU5LCJleHAiOjE2OTAzODIxNTl9.W7ZHhAt1ClBul6lAKxCjGFXG9rO2l5B1CykWRH0aGzk