GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json
    
{   
    "title": "test",
    "author": "ed-rad",
    "url": "https://www.google.com",
    "likes": 12
}

###