POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "superoot",
    "name": "Superuser",
    "password": "salained"
}

###

GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "this is my sixth note",
    "important": false,
    "userId": "64bff3b15bbca97d4b588bbb"
}

###

GET http://localhost:3001/api/notes/5f0b4a3b1c9d440000a3b0a0

###

DELETE http://localhost:3001/api/notes/64b5432b84f9d743a6334dfa

###

PUT http://localhost:3001/api/notes/64b2cffc1d512056db306fe2
content-type: application/json

{
    "content": "!Ensure that the everything still works!?",
    "important": true
}
