POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "test",
    "name": "testName",
    "password": "test"
}

###

GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0YzM4NjRjYWExOWM0YjU4ZWE3NTIwMiIsImlhdCI6MTY5MDUzNTU4MiwiZXhwIjoxNjkwNTM5MTgyfQ.b_SIKC9u-9_FElwEhMZwGRtX_oTuKlqH_3yv0cLatds

{
    "content": "this is my seventh note",
    "important": false
}

###

GET http://localhost:3001/api/notes/5f0b4a3b1c9d440000a3b0a0

###

DELETE http://localhost:3001/api/notes/64b5432b84f9d743a6334dfa

###

PUT http://localhost:3001/api/notes/64b2cffc1d512056db306fe2
content-type: application/json

{
    "content": "!Ensure that the everything still works!?",
    "important": true
}

###

post http://localhost:3001/api/login
content-type: application/json

{
    "username": "test",
    "password": "test"
}
